# railway.yml

# Set the version of the Railway environment
version: "1.0"

# Define the services and their configuration
services:
  # Define a service named "web" for your Spring Boot application
  web:
    # Set the build command for your application
    build: ./gradlew build   # Update this path to the location of your Spring Boot application
    # Set the run command for your application
    run: ./gradlew bootRun  # Update this with your actual JAR file name
    # Set the port that your application will listen on
    port: 8080  # Update this with the port number your application listens on

# Define the routes for your application
routes:
  # Define a route for the root URL ("/") to route traffic to the "web" service
  - path: /
    destination: web  # Route traffic to the "web" service

## Define any environment variables that your application needs
#env:
#  # Define an environment variable for your database connection configuration
#  DATABASE_URL: <your-database-url>  # Update this with your actual database URL
#  # Define any other environment variables your application requires
#  # ...
